language: python

python:
  - "3.4"

sudo: required

before_install:
- "sudo apt-get install graphviz"

install:
  - "pip install ablog"
  - "pip install sphinxcontrib-plantuml"

script:
  - ablog build

after_success:
  - git config --global user.name "Marco Heinemann"
  - git config --global user.email "marco.heinemann@useblocks.com"
  - git config --global push.default simple
  - ablog deploy --push-quietly --github-token=DEPLOY_KEY -m="`git log -1 --pretty=%B`"