language: python

python:
  - "3.4"

virtualenv:
    system_site_packages: true

install:
  - "pip install ablog"
  - "pip install sphinxcontrib-plantuml"

script:
  - ablog build

after_success:
  - git config --global user.name "Daniel Woste"
  - git config --global user.email "daniel.woste@useblocks.com"
  - git config --global push.default simple
  - ablog deploy --push-quietly --github-token=DEPLOY_KEY -m="`git log -1 --pretty=%B`"